#!/bin/bash

# Deploy all fixes to production server
echo "================================================================="
echo "          DEPLOYING TO PRODUCTION: ss.gonxt.tech"
echo "================================================================="
echo ""
echo "Target Server: 35.177.226.170"
echo "Deployment: Backend API + Frontend"
echo ""
echo "Recent Changes:"
echo "  ✓ Fixed customer GET by ID endpoint"
echo "  ✓ Added /api/health endpoint"
echo "  ✓ Added /api/users/profile endpoint"
echo "  ✓ Fixed E2E test routes"
echo ""
echo "================================================================="
echo ""
echo "MANUAL DEPLOYMENT STEPS:"
echo ""
echo "1. Connect to production server:"
echo "   ssh ubuntu@35.177.226.170"
echo ""
echo "2. Deploy Backend API:"
echo "   cd /home/ubuntu/salessync/backend-api"
echo "   git pull origin main"
echo "   pm2 restart backend-salessync"
echo "   pm2 logs backend-salessync --lines 50"
echo ""
echo "3. Verify backend health:"
echo "   curl -k https://ss.gonxt.tech/api/health"
echo "   curl -k https://ss.gonxt.tech/api/api/health"
echo ""
echo "4. Deploy Frontend (if needed):"
echo "   cd /home/ubuntu/salessync/frontend"
echo "   git pull origin main"
echo "   npm run build"
echo "   pm2 restart frontend-salessync"
echo ""
echo "5. Run E2E tests from local machine:"
echo "   ./production-e2e-simplified.sh"
echo ""
echo "================================================================="
echo "Target: 100% E2E Coverage (55/55 tests passing)"
echo "================================================================="
